# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 673465a3b6120f96bbe0933859c034669e4cb928c5c9d2491000d98ac82ab37146402191ca8df3e95a80b4520b1cec7e3efad6bbfa72b239475b5491e5aa314a

test:
  secret_key_base: 6ad8b4d0b52f3ed7ca54c599abad443e4ab47389d7f232470ed0b5c0c8e1cba7cff6d019c03e2a7a63baf47bc5dc35981d2a076c1da68ec95284528f084c6259

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
